### ISSUE TITLE
How to specify download path？

### ISSUE THREAD

**Issue by xmk2222** [nsrr/nsrr-gem#16]
How to specify download path？

**Comment by mrueschman** [comment]
I don't think there is a way to specify the download path. The gem uses the current directory when attempting its downloads, so in that way the user can control where files are downloaded.

For example, if I want to download the 'shhs' dataset into c:\nsrr:

![2019-12-24_13h30_42](https://user-images.githubusercontent.com/707167/71422624-9ad3ce00-2651-11ea-808f-e8ff22757533.png)

**Comment by remomueller** [comment]
Marking this as resolved, no current plan to add a download path parameter to the gem. As @mrueschman, the gem downloads the files to its current directory, and maintains the folder structure found on the NSRR.
