### ISSUE TITLE
download multiple specific files at once

### ISSUE THREAD

**Issue by fabbra** [nsrr/nsrr-gem#17]
Is there a way to download multiple - manually-specified - files at once?
Downloading one specific file works fine: `nsrr download DATASET/filename1`.
However I cannot download multiple files at once, e.g. the following does not work: `nsrr download DATASET/filename1, DATASET/filename2, DATASET/filename3, DATASET/filename5` (same issue also without comma in between the different files).

The reasoning behind is two-fold: 
a) I do not want to download the entire database for reasons of limited disk space.
b) I do not want to execute the `nsrr download` for each file individually since this forces me to enter the token each time manually and I would like to download lots of files at once without manual interaction

Thanks for your help!

**Comment by mrueschman** [comment]
Thanks for checking out the site. I have two possible workarounds. 

1. Add the "--token=<INSERT_TOKEN_HERE>" flag when running "nsrr download". E.g. "nsrr download DATASET/filename1 --token=<your_token_here>". This should get around the issue of being forced to re-enter token each time command is run.
2. Use the 'nsrr' R package (https://www.rdocumentation.org/packages/nsrr/versions/0.1.3), which stores your token behind the scenes and avoids having to re-enter it all the time.

Hope this helps! Marking the issue as closed.

**Comment by fabbra** [comment]
Using the `--token` flag works perfect for me, thanks!
