### ISSUE TITLE
Test compatibility of gem with Ruby 3.0+

### ISSUE THREAD

**Issue by mrueschman** [nsrr/nsrr-gem#19]
User reported issues downloading from a dataset despite having the right token and coming through as "AUTHORIZED". I had the user test with the 'learn' dataset, which is public and should download with or without a proper token.

![image](https://user-images.githubusercontent.com/707167/103657511-ffe62300-4f37-11eb-9ebb-edc86b93e866.png)

I asked the user to try Ruby 2.7.X and after installing this the gem is working as expected across datasets.

User was using Ruby 3.0.0-1 on Windows 10.

**Comment by remomueller** [comment]
Ruby 3.0.0 compatibility added in [nsrr 6.0.0](https://rubygems.org/gems/nsrr/versions/6.0.0). https://github.com/nsrr/nsrr-gem/commit/4d8b23fa0c2352e89ef32b00418675f3f936130e
