### ISSUE TITLE
Can we directly download the data set in Ubuntu? I don't know how to install nsrr in ubuntu.

### ISSUE THREAD

**Issue by NNPanNPU** [nsrr/nsrr-gem#21]

**Comment by mrueschman** [comment]
Yes, you can download NSRR datasets in Ubuntu after installing the NSRR gem.

The instructions are included in the gem README: https://github.com/nsrr/nsrr-gem

Install Ruby, install gem, run "nsrr download <dataset>" commands. You will need an approved data request to download certain datasets, e.g. https://sleepdata.org/data/requests/shhs/start

Good luck!
